Test/ci test
Issei0804-ie/Uhyo pull request #42
Opened 2020-03-08 14:47 UTC by sinnchan

# くわしく
AndroidのUnitTest作成しました
とても、とてもしんどかったです。

2020-03-08 14:48 UTC, sinnchan commented
@Issei0804-ie 君のCIが何故か動いてるけど関係ないです。

2020-03-09 12:55 UTC, Issei0804-ie requested changes

2020-03-09 12:55 UTC, Issei0804-ie commented on .github/workflows/android_unit_test.yml
> +      run: echo $(ls)
確認用で作ったと思うんだけど、消した方がよくないっすか！

2020-03-09 12:55 UTC, Issei0804-ie commented on .github/workflows/android_unit_test.yml
> +      run: echo $(ls)
@sinnchan

2020-03-09 13:12 UTC, merged

2020-03-09 13:12 UTC, Issei0804-ie commented
![LGTM_dandast3](https://user-images.githubusercontent.com/52270000/76215887-fc6c0780-6252-11ea-96bf-a96732827873.jpg)